const main = async () => {}

main().catch(x => {
	console.log('# something happens.')
	console.error(x)
})
